project:
  type: book

jupyter: python3
engine: knitr
book:
  title: "Analytics for Accounting Data"
  reader-mode: true
  date: today
  date-format: long 
  author: 
  - name: "Sharif Islam, DBA, CPA, CMA"
    email: mdshariful.islam@siu.edu 
    affiliations: 
      - name: "Southern Illinois University Carbondale"
        
  page-footer:
    left: |
      Copyright©Sharif Islam
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - part: "Introduction to Accounting Analytics"
      chapters:
        - overview.qmd
        - foundations.qmd
    - part: "Data Exploration and Management"
      chapters:
        - eda.qmd 
        - visualization.qmd 
        - dashboard.qmd
        - data_management.qmd
    - part: "Predictive and Prescriptive Analytics"
      chapters: 
        - predictive.qmd
        - prescriptive.qmd 
    - part: "Advanced Techniques and Applications"
      chapters:
        - advanced_analytics.qmd
        - nlp.qmd 
        - machine_learning.qmd
        - fraud.qmd
        - performance_measurement.qmd
    - part: "Practical Considerations and Future Directions"
      chapters: 
        - ethics.qmd
        - future.qmd
  appendices: 
    - python_basics.qmd
    - r_basics.qmd
    - chapter1_solution.qmd
    - chapter2_solution.qmd

    - references.qmd
    
    
number-depth: 5  
site-url: https://analyticsforaccountingdata.netlify.app/
repo-url: https://github.com/msharifbd/sharifanalytics
repo-actions: [edit, issue]
repo-branch: main
sharing: [twitter, facebook, linkedin]
downloads: [pdf, epub]
bibliography: references.bib


format:
  html:
    theme: flatly
    mainfont: Georgia, serif 
    code-link: true
    callout-appearance: default
    cover-image: images/titlepage_1_alt.webp

  pdf:
    documentclass: scrreprt
    output-file: pdf-book
    pdf-engine: xelatex
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    colorlinks: true

    

editor: visual