#!C:\Users\mshar\OneDrive - Southern Illinois University\ANALYTICS_FOR_ACCOUNTING_DATA\accounting_analytics_book\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
